version: "3"

services:
  zf:
    build:
      context: .
      dockerfile: docker/zend/Dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: .env
    container_name: zend_php
    ports:
     - "8089:80"
    volumes:
     - .:/var/www
    links:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  mysql:
    build:
      context: ./Docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zend_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "8989:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql


